name: Upload to DO Spaces

on:
  push:
    branches: [main]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY}}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: reveni-prod
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: lib/reveni-js-sdk.js
          out_dir: js
          versioning: true
