name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REACT_APP_HOST: http://localhost:8000
  REACT_APP_BACKEND_HOST: http://localhost:8000

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Bun.sh 1.0.0
        if: steps.cache.outputs.cache-hit != 'true'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0

      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun install

  linter:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Bun.sh 1.0.0
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: bun run linter

  tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Bun.sh 1.0.0
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: bun run test:ci

      - name: report coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 90
          github-token: ${{ secrets.GITHUB_TOKEN }}
